---
title: "p8105_hw3_nz2333"
author: "nz2333"
date: "10/20/2021"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
data("instacart")
```

_Problem 1_

#Question1
```{r}
aisles = instacart %>%
  count(aisle, sort = TRUE)

aisles
```
/There are total 134 aisles in the data. The aisle with most n is "fresh vegetables", with 150609 items./

#Question2
```{r}
aisles2 = instacart %>%
  count(aisle, sort = TRUE)%>%
  filter(n > 10000)

ggplot(data = aisles2, aes(x = reorder(aisle, -n), y = n))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(title = "Number of Items in each aisle")+
  xlab("Aisles")+
  ylab("Items Count")
```

#Question3
```{r}
instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")
  )%>%
  group_by(aisle, product_name)%>%
  summarize(
    item_num = n()
  )%>%
  mutate(
    item_rank = min_rank(-item_num)
  )%>%
  filter(item_rank < 4) %>%
  select(-item_rank) %>%
  knitr::kable()
```

